version: '3.5'

services:
  postgres:
    image: postgres
    platform: linux/arm/v8
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "pierpont"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pierpont

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres/pierpont -user=postgres -password=postgres migrate
    volumes:
      - ${PWD}/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - "postgres"
    networks:
      - pierpont

  pierpont:
#    image: pierpont:1.0.0
    build: .
    environment:
      DATABASE_JDBC_URL: "jdbc:postgresql://postgres:5432/pierpont"
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "postgres"
      JAVA_OPTS: "-Ddebug -Xmx128m"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - "postgres"
      - "flyway"
    networks:
      - pierpont

networks:
  pierpont:

volumes:
  postgres:
