server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json
  servlet:
    context-path: /api/v1

spring:
  application:
    name: "Pierpont - API"
  jpa:
    show-sql: false
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://192.168.64.1:5432/pierpont"
    username: "postgres"
    password: "postgres"

#    DATABASE_JDBC_URL=jdbc:postgresql://192.168.64.1:5432/pierpont;POSTGRES_PASSWORD=postgres;POSTGRES_USER=postgres;JAVA_OPTS=-Ddebug -Xmx128m

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: "always"
      group:
        liveness:
          include: "livenessState"
        readiness:
          include: "readinessState, db, diskSpace"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true