name: Basic validation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Compile with Maven
        run: mvn clean compile
      - name: Package with Maven
        run: mvn package
      - name: Tests with Maven
        run: mvn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/jacoco.xml
          flags: jacoco
          fail_ci_if_error: true
      - name: Integration tests
        run: |
          docker-compose down
          docker volume rm pierpont_postgres || true
          docker-compose build --no-cache
          docker-compose up -d
          docker run \
            -v "${PWD}"/src/main/resources/Pierpont.postman_collection.json:/etc/postman/Pierpont.postman_collection.json \
            --network pierpont_pierpont \
            -t postman/newman \
            run /etc/postman/Pierpont.postman_collection.json --env-var "BASE_URL=pierpont:8080"
