name: Basic validation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: pierpont
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Compile with Maven
        run: mvn clean compile
      - name: Package with Maven
        run: mvn package
      - name: Tests with Maven
        run: mvn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/jacoco.xml
          flags: jacoco
          fail_ci_if_error: true
      - name: Flyway migration
        run: docker run -v ${PWD}/src/main/resources/db/migration:/flyway/sql -t flyway/flyway -url=jdbc:postgresql://postgres:5432/pierpont -user=postgres -password=postgres migrate

#        uses: docker://flyway/flyway:9
#        env:
#          FLYWAY_URL: jdbc:postgresql://postgres:5432/pierpont
#          FLYWAY_USER: postgres
#          FLYWAY_PASSWORD: postgres
#          FLYWAY_LOCATIONS: filesystem:./sql
#          FLYWAY_VALIDATE_MIGRATION_NAMING: true
#        uses: joshuaavalon/flyway-action@v3.0.0
#        with:
#          url: jdbc:postgresql://postgres:5432/pierpont
#          user: postgres
#          password: postgres
#          locations: ./src/main/resources/db/migration
#        env:
#          FLYWAY_VALIDATE_MIGRATION_NAMING: true


#      - name: Install Node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 20
#      - name: Install Newman
#        run: npm install -g newman
#      - uses: adambirds/docker-compose-action@v1.3.0
#        with:
#          compose-file: "./docker-compose.yaml"
#      - name: Integration tests
#        run: ./integration-test.sh
